In [1]:
import numpy as np

In [2]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [3]:
np.array([1, 2, 3, 4, 5]) + 10

array([11, 12, 13, 14, 15])

In [4]:
np.array([1, 2, 3, 4, 5]).shape

(5,)

In [7]:
# Multi-dimensional array
np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
np.array([[1, 2, 3, 4], [5, 6, 7, 8]]).shape

(2, 4)

In [10]:
np.array([[1, 2, 3, 4], [5, 6, 7, 8]])[0]

array([1, 2, 3, 4])

In [11]:
np.array([[1, 2, 3, 4], [5, 6, 7, 8]])[0][-1]

4

In [13]:
# First column
np.array([[1, 2, 3, 4], [5, 6, 7, 8]])[:, 0]

array([1, 5])

In [14]:
# First row
np.array([[1, 2, 3, 4], [5, 6, 7, 8]])[0, :]

array([1, 2, 3, 4])

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])